import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <header className="sticky top-0 z-10 w-full shadow-md">QR Example</header>
        <main className="flex-grow overflow-y-auto flex flex-col items-center p-5 font-[family-name:var(--font-geist-sans)]">
          {children}
        </main>
        <footer className="border-t border-gray-400 text-gray-400 py-4 text-center w-full">
          <p className="text-sm sm:text-base">© User App</p>
        </footer>
      </body>
    </html>
  );
}
